export type SaveState = 'saved' | 'saving' | 'dirty' | 'error'
export interface Segment { id: string; order: number; text: string; marks: Record<string, unknown>[]; text_color: string | null; background_asset_id: string | null; background_motion: string | null; background_position_x: number; background_position_y: number; tts_audio_asset_id: string | null; audio_duration_ms: number | null; status: string }
export interface Project { id: string; name: string; canvas: { width: number; height: number; fps: number; segment_duration?: number; font_size?: number; font_path?: string; heartbeat_interval_ms?: number; caption_position_y?: number; background_color: string }; template_id: string; tts_settings: Record<string, unknown>; bgm_settings: Record<string, unknown>; created_at: string; updated_at: string; segments: Segment[] }
export type ProjectSummary = Pick<Project, 'id' | 'name' | 'template_id' | 'created_at' | 'updated_at'>
export interface Job { id: string; project_id: string; target_segment_id: string | null; result_asset_id: string | null; type: string; status: string; progress: number; stage: string; error_message: string | null; created_at: string; started_at: string | null; finished_at: string | null }
export interface WorkerStatus { online: boolean; pid: number | null; current_job_id: string | null; updated_at: string | null; stale_seconds: number | null; heartbeat_file: string }
export interface ModelStatus { qwen_available: boolean; qwen_model_dir: string; qwen_python: string; omnivoice_available: boolean; omnivoice_project_dir: string; omnivoice_python: string; ffmpeg_available: boolean; ffmpeg_path: string; ancient_voice_available: boolean; ancient_voice_path: string; ancient_font_available: boolean; ancient_font_path: string; ancient_reference_text: string }
export interface Asset { id: string; project_id: string | null; kind: string; original_name: string; storage_path: string; mime_type: string; size: number; duration_ms: number | null; sha256: string; created_at: string }
export interface MusicTrack { id: string; name: string; path: string; mood: string; bpm: number }
export interface VoicePreset { id: string; name: string; path: string; reference_text: string }
